add the BASIC_AUTHENTICATION_UNAUTHORIZED response template
gravitee-io/gravitee-policy-basic-authentication pull request #23
Opened 2022-04-05 19:56 UTC by yurkovandrey

**Issue**

https://github.com/gravitee-io/issues/issues/7458

**Description**

add the **BASIC_AUTHENTICATION_UNAUTHORIZED** response template to override the default responses provided by the policy

**Additional context**
I've tested the changes with the graviteeio/apim-gateway:3.15.4 docker image using additionally the **inline auth provider (v1.3.0)** as an identity provider for the basic auth policy

2022-04-06 12:21 UTC, gaetanmaisse commented
Quick message @yurkovandrey to tell you we will review this PR soon too!

2022-05-10 05:56 UTC, marcambier requested changes
Thanks a lot for your contribution @yurkovandrey !
Here are some comments for your pull request.

2022-05-10 05:56 UTC, marcambier commented on src/main/java/io/gravitee/policy/basicauth/BasicAuthenticationPolicy.java
> +                Maps.<String, Object>builder().put("path", request.path()).put("method", request.method()).build()
If you want to display path and method in your response template, you can use `{#request.path}` and `{#request.method}`.
I don't think we need to add those extra parameters.
Can we remove them ?

2022-05-10 05:56 UTC, marcambier commented on src/main/java/io/gravitee/policy/basicauth/BasicAuthenticationPolicy.java
> +                Maps.<String, Object>builder().put("path", request.path()).put("method", request.method()).build()
If you want to display path and method in your response template, you can use `{#request.path}` and `{#request.method}`.
I don't think we need to add those extra parameters.
Can we remove them ?

2022-05-10 05:56 UTC, marcambier commented on src/main/java/io/gravitee/policy/basicauth/BasicAuthenticationPolicy.java
> +    private static final String BASIC_AUTHENTICATION_UNAUTHORIZED = "BASIC_AUTHENTICATION_UNAUTHORIZED";
To keep consistency between our policies, we could fit the behavior of the API Key policy, which returns 2 distinct error keys : [see doc](https://docs.gravitee.io/apim/3.x/apim_publisherguide_response_templates.html#policy_error_keys_you_can_override)

Maybe we could keep the same pattern, and have something like :
- BASIC_AUTHENTICATION_MISSING
- BASIC_AUTHENTICATION_INVALID

WDYT ?

2022-05-10 05:56 UTC, marcambier commented on src/main/java/io/gravitee/policy/basicauth/BasicAuthenticationPolicy.java
> +    private static final String BASIC_AUTHENTICATION_UNAUTHORIZED = "BASIC_AUTHENTICATION_UNAUTHORIZED";
To keep consistency between our policies, we could fit the behavior of the API Key policy, which returns 2 distinct error keys : [see doc](https://docs.gravitee.io/apim/3.x/apim_publisherguide_response_templates.html#policy_error_keys_you_can_override)

Maybe we could keep the same pattern, and have something like :
- BASIC_AUTHENTICATION_MISSING
- BASIC_AUTHENTICATION_INVALID

WDYT ?

2023-02-13 13:56 UTC, gaetanmaisse commented
Closing as it didn't get any update for a while

2023-02-13 13:56 UTC, closed without merging